/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package development.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author somenath
 */
public class upr extends javax.swing.JFrame {

    /**
     * Creates new form upr
     */
    public upr() {
        initComponents();
        uptabel();
    }
     public void uptabel(){
       try {
           
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/software?useTimezone=true&serverTimezone=UTC", "root", "");
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("select * from registration ");
               tb.setModel(DbUtils.resultSetToTableModel(rs));
            
       } catch (Exception e) {
           
           JOptionPane.showMessageDialog(null, e);
       }
       
   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        src = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        Complete = new javax.swing.JRadioButton();
        Partially = new javax.swing.JRadioButton();
        Pending = new javax.swing.JRadioButton();
        Search1 = new javax.swing.JButton();
        Search2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        t = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTable();
        Search3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 5));

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb);

        src.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcActionPerformed(evt);
            }
        });

        Search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Search.setText("SEARCH");
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
        });

        Complete.setBackground(new java.awt.Color(0, 153, 0));
        buttonGroup1.add(Complete);
        Complete.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Complete.setText(" Complete");

        Partially.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(Partially);
        Partially.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Partially.setText("Partially Complete");

        Pending.setBackground(new java.awt.Color(255, 102, 102));
        buttonGroup1.add(Pending);
        Pending.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Pending.setText("Pending");
        Pending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingActionPerformed(evt);
            }
        });

        Search1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Search1.setText("UPDATE");
        Search1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search1MouseClicked(evt);
            }
        });
        Search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search1ActionPerformed(evt);
            }
        });

        Search2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Search2.setText("GO BACK");
        Search2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search2MouseClicked(evt);
            }
        });

        t.setColumns(20);
        t.setRows(5);
        jScrollPane2.setViewportView(t);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Registration Update");

        t2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(t2);

        Search3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Search3.setText("DELETE");
        Search3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Search3MouseClicked(evt);
            }
        });
        Search3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Search2)
                                .addGap(51, 51, 51)
                                .addComponent(Search3)
                                .addGap(60, 60, 60)
                                .addComponent(Search1)
                                .addGap(303, 303, 303))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(src, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(Search)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Pending)
                                        .addGap(18, 18, 18)
                                        .addComponent(Partially)
                                        .addGap(18, 18, 18)
                                        .addComponent(Complete)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(src)
                            .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Complete)
                            .addComponent(Partially)
                            .addComponent(Pending)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srcActionPerformed

    private void PendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PendingActionPerformed

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        // TODO add your handling code here:
        
                      try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/software?useTimezone=true&serverTimezone=UTC", "root", "");
            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery("select * from registration where id = '"+src.getText()+"'");
            
              if(rs.next()){  
                   sl=rs.getString("slno");
                id = rs.getString("ID");
                nam = rs.getString("Name");
                String sta = rs.getString("Status");
                 txt(sta);
                 uptabel2();

           }
              
              else
                 JOptionPane.showMessageDialog(null,"You Input Wrong ID");
               
               
        } catch (ClassNotFoundException | SQLException e) {
            
        } 
                   
    }//GEN-LAST:event_SearchMouseClicked

        public void uptabel2(){
       try {
           
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/software?useTimezone=true&serverTimezone=UTC", "root", "");
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("select * from c where id = '"+src.getText()+"'");
               t2.setModel(DbUtils.resultSetToTableModel(rs));
            
       } catch (Exception e) {
           
           JOptionPane.showMessageDialog(null, e);
       }
       
   }
    void txt(String x){
        
                t.setText(" ID : "+id+"\n Name : "+nam+"\n  Status : "+x);
    }
    private void Search1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search1MouseClicked
        // TODO add your handling code here:
        
      try{
           
            Class.forName("com.mysql.cj.jdbc.Driver");
            var con = DriverManager.getConnection("jdbc:mysql://localhost:3306/software?useTimezone=true&serverTimezone=UTC", "root", "");
            String sql = "UPDATE registration SET ID =?,Name =?,Status =?  where slno="+sl;
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,id);
            pst.setString(2,nam);
             if(Pending.isSelected()){
                c = "Pending";
            }
            if(Partially.isSelected()){
                c = "Partially Complete";
               
            }
             if(Complete.isSelected()){
                c = "Complete";
                        }
           
            pst.setString(3,c);
            
            
            
            pst.executeUpdate();
            txt(c);
          uptabel();
            
            
                      
                   
                 JOptionPane.showMessageDialog(null, "Done");
          }   
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           
       }
    }//GEN-LAST:event_Search1MouseClicked

    private void Search2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search2MouseClicked
        // TODO add your handling code here:
        
        r obj = new r();
                 obj.setVisible(true);
                 obj.pack();
                 obj.setLocationRelativeTo(null);
                 obj.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                 this.dispose();
    }//GEN-LAST:event_Search2MouseClicked

    private void Search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search1ActionPerformed

    private void Search3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search3MouseClicked
  try{
           
            Class.forName("com.mysql.cj.jdbc.Driver");
            var con = DriverManager.getConnection("jdbc:mysql://localhost:3306/software?useTimezone=true&serverTimezone=UTC", "root", "");
            String sql = "DELETE FROM registration where slno="+sl;
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            txt();
            uptabel();
               
            JOptionPane.showMessageDialog(null, "Done");
          }   
    catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           
       }        // TODO add your handling code here:
        
     
        
    }//GEN-LAST:event_Search3MouseClicked
void txt(){
    
}
    private void Search3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void mainup() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(upr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(upr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(upr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(upr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new upr().setVisible(true);
            }
        });
    }
String c,id,nam,sl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Complete;
    private javax.swing.JRadioButton Partially;
    private javax.swing.JRadioButton Pending;
    private javax.swing.JButton Search;
    private javax.swing.JButton Search1;
    private javax.swing.JButton Search2;
    private javax.swing.JButton Search3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField src;
    private javax.swing.JTextArea t;
    private javax.swing.JTable t2;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
